language: php
dist: trusty
sudo: false
php:
  - 7.2
  - 7.1
cache:
  directories:
    - $HOME/.composer/cache
install:
  - composer install --no-interaction
script:
  - ./vendor/bin/phpunit --coverage-clover ./build/logs/clover.xml
after_script:
  - php vendor/bin/php-coveralls -v