<?php

namespace Platformsh\Client\Tests\Model;


use Platformsh\Client\Model\Account;
use Platformsh\Client\Tests\PlatformshTestBase;
use Platformsh\Client\Model\ProjectAccess;

class ProjectAccessTest extends PlatformshTestBase
{

    /** @var ProjectAccess */
    private $projectAccess;

    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $project = $this->client->getProject('test', 'example.com');
        $this->projectAccess = $project->getUsers()[0];


    }

    public function testGetters() {
        $this->assertEquals($this->testProjectAccess[0]['id'], $this->projectAccess->id, 'Id property getter');
        $this->assertEquals($this->testProjectAccess[0]['user'], $this->projectAccess->user, 'User property getter');
        $this->assertEquals($this->testProjectAccess[0]['role'], $this->projectAccess->role, 'Role property getter');
    }

    public function testGetAccount() {
        $this->assertInstanceOf(Account::class, $this->projectAccess->getAccount());
    }
//    public function testChangeEnvironmentRole() {}
//    public function testGetSshKeys() {}
//    public function testAddSshKey() {}
//    public function testCheckProperty() {}
//    public function testIsEditable() {}
//    public function testDelete() {}
}



